# Generated by Django 4.2.1 on 2023-05-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_alter_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
