# Generated by Django 4.2.1 on 2023-05-22 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoModel',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PostModel',
        ),
    ]
